/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface XmichaliklEquipmentApp {
    }
}
declare global {
    interface HTMLXmichaliklEquipmentAppElement extends Components.XmichaliklEquipmentApp, HTMLStencilElement {
    }
    var HTMLXmichaliklEquipmentAppElement: {
        prototype: HTMLXmichaliklEquipmentAppElement;
        new (): HTMLXmichaliklEquipmentAppElement;
    };
    interface HTMLElementTagNameMap {
        "xmichalikl-equipment-app": HTMLXmichaliklEquipmentAppElement;
    }
}
declare namespace LocalJSX {
    interface XmichaliklEquipmentApp {
    }
    interface IntrinsicElements {
        "xmichalikl-equipment-app": XmichaliklEquipmentApp;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "xmichalikl-equipment-app": LocalJSX.XmichaliklEquipmentApp & JSXBase.HTMLAttributes<HTMLXmichaliklEquipmentAppElement>;
        }
    }
}
